# This workflow will build a Java project with Gradle

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Build with Java 1.8
        run: |
          ./gradlew --version
          ./gradlew test --info

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Java 11
        run: |
          ./gradlew --version
          ./gradlew test --info

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - name: Build with Java 16
        run: |
          ./gradlew --version
          ./gradlew test --info

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        if: always() && (github.ref == 'refs/heads/main')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'

